[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  # Ensure devDependencies are installed for Tailwind/PostCSS
  NPM_FLAGS = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
